
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<ClientOptions extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions, Log = $Class.LogOptions<ClientOptions>, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<ClientOptions, Log, ExtArgs>
export { Prisma }



/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Manga
 * 
 */
export type Manga = Prisma.MangaModel
/**
 * Model Author
 * 
 */
export type Author = Prisma.AuthorModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model Chapter
 * 
 */
export type Chapter = Prisma.ChapterModel
/**
 * Model MangaAuthor
 * 
 */
export type MangaAuthor = Prisma.MangaAuthorModel

export type Role = $Enums.Role
export const Role = $Enums.Role

export type StatusEnum = $Enums.StatusEnum
export const StatusEnum = $Enums.StatusEnum

export type ContentRatingEnum = $Enums.ContentRatingEnum
export const ContentRatingEnum = $Enums.ContentRatingEnum

export type StateEnum = $Enums.StateEnum
export const StateEnum = $Enums.StateEnum

export type DemographicEnum = $Enums.DemographicEnum
export const DemographicEnum = $Enums.DemographicEnum

export type TagGroupEnum = $Enums.TagGroupEnum
export const TagGroupEnum = $Enums.TagGroupEnum

export type MangaAuthorRoleEnum = $Enums.MangaAuthorRoleEnum
export const MangaAuthorRoleEnum = $Enums.MangaAuthorRoleEnum
