
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import type * as Prisma from "./internal/prismaNamespace.ts"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumDemographicEnumNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.DemographicEnum | Prisma.EnumDemographicEnumFieldRefInput<$PrismaModel> | null
  in?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel> | $Enums.DemographicEnum | null
}

export type EnumStatusEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel> | $Enums.StatusEnum
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumContentRatingEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentRatingEnum | Prisma.EnumContentRatingEnumFieldRefInput<$PrismaModel>
  in?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel> | $Enums.ContentRatingEnum
}

export type EnumStateEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StateEnum | Prisma.EnumStateEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStateEnumFilter<$PrismaModel> | $Enums.StateEnum
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumDemographicEnumNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DemographicEnum | Prisma.EnumDemographicEnumFieldRefInput<$PrismaModel> | null
  in?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDemographicEnumNullableWithAggregatesFilter<$PrismaModel> | $Enums.DemographicEnum | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel>
}

export type EnumStatusEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel> | $Enums.StatusEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumContentRatingEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentRatingEnum | Prisma.EnumContentRatingEnumFieldRefInput<$PrismaModel>
  in?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentRatingEnumWithAggregatesFilter<$PrismaModel> | $Enums.ContentRatingEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel>
}

export type EnumStateEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StateEnum | Prisma.EnumStateEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStateEnumWithAggregatesFilter<$PrismaModel> | $Enums.StateEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStateEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStateEnumFilter<$PrismaModel>
}

export type JsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>
}

export type EnumTagGroupEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.TagGroupEnum | Prisma.EnumTagGroupEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel> | $Enums.TagGroupEnum
}

export type EnumTagGroupEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TagGroupEnum | Prisma.EnumTagGroupEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTagGroupEnumWithAggregatesFilter<$PrismaModel> | $Enums.TagGroupEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel>
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumMangaAuthorRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.MangaAuthorRoleEnum | Prisma.EnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel> | $Enums.MangaAuthorRoleEnum
}

export type EnumMangaAuthorRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MangaAuthorRoleEnum | Prisma.EnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMangaAuthorRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.MangaAuthorRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumDemographicEnumNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.DemographicEnum | Prisma.EnumDemographicEnumFieldRefInput<$PrismaModel> | null
  in?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel> | $Enums.DemographicEnum | null
}

export type NestedEnumStatusEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel> | $Enums.StatusEnum
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumContentRatingEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentRatingEnum | Prisma.EnumContentRatingEnumFieldRefInput<$PrismaModel>
  in?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel> | $Enums.ContentRatingEnum
}

export type NestedEnumStateEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.StateEnum | Prisma.EnumStateEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStateEnumFilter<$PrismaModel> | $Enums.StateEnum
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedEnumDemographicEnumNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DemographicEnum | Prisma.EnumDemographicEnumFieldRefInput<$PrismaModel> | null
  in?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.DemographicEnum[] | Prisma.ListEnumDemographicEnumFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDemographicEnumNullableWithAggregatesFilter<$PrismaModel> | $Enums.DemographicEnum | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDemographicEnumNullableFilter<$PrismaModel>
}

export type NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StatusEnum | Prisma.EnumStatusEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StatusEnum[] | Prisma.ListEnumStatusEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStatusEnumWithAggregatesFilter<$PrismaModel> | $Enums.StatusEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStatusEnumFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumContentRatingEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ContentRatingEnum | Prisma.EnumContentRatingEnumFieldRefInput<$PrismaModel>
  in?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.ContentRatingEnum[] | Prisma.ListEnumContentRatingEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumContentRatingEnumWithAggregatesFilter<$PrismaModel> | $Enums.ContentRatingEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumContentRatingEnumFilter<$PrismaModel>
}

export type NestedEnumStateEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StateEnum | Prisma.EnumStateEnumFieldRefInput<$PrismaModel>
  in?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.StateEnum[] | Prisma.ListEnumStateEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumStateEnumWithAggregatesFilter<$PrismaModel> | $Enums.StateEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStateEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStateEnumFilter<$PrismaModel>
}

export type NestedJsonNullableFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonNullableFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonNullableFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedEnumTagGroupEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.TagGroupEnum | Prisma.EnumTagGroupEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel> | $Enums.TagGroupEnum
}

export type NestedEnumTagGroupEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TagGroupEnum | Prisma.EnumTagGroupEnumFieldRefInput<$PrismaModel>
  in?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.TagGroupEnum[] | Prisma.ListEnumTagGroupEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTagGroupEnumWithAggregatesFilter<$PrismaModel> | $Enums.TagGroupEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTagGroupEnumFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel = never> = {
  equals?: $Enums.MangaAuthorRoleEnum | Prisma.EnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel> | $Enums.MangaAuthorRoleEnum
}

export type NestedEnumMangaAuthorRoleEnumWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MangaAuthorRoleEnum | Prisma.EnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  in?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  notIn?: $Enums.MangaAuthorRoleEnum[] | Prisma.ListEnumMangaAuthorRoleEnumFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMangaAuthorRoleEnumWithAggregatesFilter<$PrismaModel> | $Enums.MangaAuthorRoleEnum
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMangaAuthorRoleEnumFilter<$PrismaModel>
}


