
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const Role = {
  reader: 'reader',
  admin: 'admin'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const StatusEnum = {
  ongoing: 'ongoing',
  completed: 'completed',
  hiatus: 'hiatus',
  cancelled: 'cancelled'
} as const

export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum]


export const ContentRatingEnum = {
  safe: 'safe',
  suggestive: 'suggestive',
  erotica: 'erotica',
  pornographic: 'pornographic'
} as const

export type ContentRatingEnum = (typeof ContentRatingEnum)[keyof typeof ContentRatingEnum]


export const StateEnum = {
  draft: 'draft',
  published: 'published',
  submitted: 'submitted',
  rejected: 'rejected'
} as const

export type StateEnum = (typeof StateEnum)[keyof typeof StateEnum]


export const DemographicEnum = {
  shounen: 'shounen',
  shoujo: 'shoujo',
  seinen: 'seinen',
  josei: 'josei'
} as const

export type DemographicEnum = (typeof DemographicEnum)[keyof typeof DemographicEnum]


export const TagGroupEnum = {
  genre: 'genre',
  theme: 'theme',
  format: 'format',
  content: 'content'
} as const

export type TagGroupEnum = (typeof TagGroupEnum)[keyof typeof TagGroupEnum]


export const MangaAuthorRoleEnum = {
  author: 'author',
  artist: 'artist'
} as const

export type MangaAuthorRoleEnum = (typeof MangaAuthorRoleEnum)[keyof typeof MangaAuthorRoleEnum]
