
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.ts'
export type * from './models/Manga.ts'
export type * from './models/Author.ts'
export type * from './models/Tag.ts'
export type * from './models/Chapter.ts'
export type * from './models/MangaAuthor.ts'
export type * from './commonInputTypes.ts'